#!/bin/bash

version=`cat install.html | grep '<b>' | head -n1 | awk '{ print $4 }'`
echo "g.version = '$version';" > 'functions/version_auto.js'

vMajor=${version%.*}

FILE="script.$vMajor.js"
TMP="/tmp/si.js"

js_update.php $FILE

cat $FILE | sed -e 's/\(^\|};\)window./\1var /g' > $TMP

mv $TMP $FILE
